### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ValidateAIConfigurationResponse
name: "ValidateAIConfigurationResponse"
type: complextype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement ValidateAIConfigurationResponse ComplexType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: bc31dfa7-c153-4595-b6bf-af37b520139a
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the Web API ValidateAIConfigurationResponse ComplexType."
namespace: Microsoft.Dynamics.CRM
# This complex type doesn't inherit from another complextype.
description: "" 
properties:
  description: "The properties of a complex type contain the structured data of the type."
  property_items:
  - name: result
    type: Edm.String
    nullable: true
    unicode: false
    description: ""
    iscollection: false
# This complex type doesn't have any navigation properties.
usedby:
  description: "The following use the ValidateAIConfigurationResponse ComplexType."
  usedby_items:
  - name: Microsoft.Dynamics.CRM.ValidateAIConfiguration
    used_as: ReturnType
# This complex type has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex
