### YamlMime:OData
uid: Microsoft.Dynamics.CRM.attributeimageconfig
name: "attributeimageconfig"
type: entitytype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement attributeimageconfig EntityType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: f88729aa-1b7e-4767-9529-df8bc192e8e6
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the attributeimageconfig entitytype."
description: "Store configuration for each image attribute"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/attributeimageconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Image Attribute Configuration
  primary_key: attributeimageconfigid
  primary_name_attribute: attributelogicalname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: attributeimageconfigid
      type: Edm.Guid
      display_name: "AttributeImageConfig"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: attributelogicalname
      type: Edm.String
      display_name: "AttributeLogicalName"
      description: "Logical name of image attribute"
      iscomputed: false
      isreadonly: false
    - name: canstorefullimage
      type: Edm.Boolean
      display_name: "CanStoreFullImage"
      description: "Indicates if an image attribute can store full image"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: parententitylogicalname
      type: Edm.String
      display_name: "ParentEntityLogicalName"
      description: "Parent entity logical name"
      iscomputed: false
      isreadonly: false
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version number of Image Attribute Configuration."
      iscomputed: false
      isreadonly: true
# This entity has no lookup properties
# This entity has no single-valued navigation properties
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: attributeimageconfig_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_attributeimageconfig
  - name: attributeimageconfig_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_attributeimageconfig
  - name: attributeimageconfig_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_attributeimageconfig
  - name: attributeimageconfig_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_attributeimageconfig
  - name: attributeimageconfig_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_attributeimageconfig
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the attributeimageconfig entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the attributeimageconfig entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_ImageConfiguration
    description: ""
# This entity has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex