### YamlMime:OData
uid: Microsoft.Dynamics.CRM.entityanalyticsconfig
name: "entityanalyticsconfig"
type: entitytype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement entityanalyticsconfig EntityType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 8a511d50-a437-48b9-a445-1bc6ae1c250e
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the entityanalyticsconfig entitytype."
description: "This entity contains information about which entities are enabled for Azure Data Lake Services integration"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/entityanalyticsconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Entity Analytics Config
  primary_key: entityanalyticsconfigid
  primary_name_attribute: parententitylogicalname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: entityanalyticsconfigid
      type: Edm.Guid
      display_name: "Entity Analytics Config"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: isenabledforadls
      type: Edm.Boolean
      display_name: "Is Enabled For ADLS"
      description: "Azure Data Lake Storage is enabled for the selected entity"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: parententitylogicalname
      type: Edm.String
      display_name: "Entity Logical Name For Analytics"
      description: "Entity Logical Name For Analytics"
      iscomputed: false
      isreadonly: false
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version number of Entity Analytics Config."
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _organizationid_value
    single_valued_navigation_property:
    - organizationid
    description: "Unique identifier for the organization"
  - name: _parententityid_value
    single_valued_navigation_property:
    - parententityid
    description: "Unique identifier for Entity associated with Entity Analytics Config."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: organizationid
    type: Microsoft.Dynamics.CRM.organization
    partner: organization_entityanalyticsconfig
  - name: parententityid
    type: Microsoft.Dynamics.CRM.entity
    partner: entity_entityanalyticsconfig
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: entityanalyticsconfig_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_entityanalyticsconfig
  - name: entityanalyticsconfig_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_entityanalyticsconfig
  - name: entityanalyticsconfig_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_entityanalyticsconfig
  - name: entityanalyticsconfig_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_entityanalyticsconfig
  - name: entityanalyticsconfig_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_entityanalyticsconfig
# This entity has no derived entities.
# This entity has no operations
solutions:
  description: "The following solutions include the entityanalyticsconfig entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.AdvancedAnalyticsInfra
    description: ""
# This entity has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex