### YamlMime:OData
uid: Microsoft.Dynamics.CRM.entityimageconfig
name: "entityimageconfig"
type: entitytype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement entityimageconfig EntityType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 611baf3b-d4e6-4659-92a0-e3e3ae2fc85c
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the entityimageconfig entitytype."
description: "Store image configuration for each entity"
header:
  entity_set_path: "[organization URI]/api/data/v9.0/entityimageconfigs"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Entity Image Configuration
  primary_key: entityimageconfigid
  primary_name_attribute: parententitylogicalname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentidunique
      type: Edm.Guid
      display_name: "Row id unique"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: entityimageconfigid
      type: Edm.Guid
      display_name: "Entity Image Configuration"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: parententitylogicalname
      type: Edm.String
      display_name: "ParentEntityLogicalName"
      description: "Parent entity logical name"
      iscomputed: false
      isreadonly: false
    - name: primaryimageattribute
      type: Edm.String
      display_name: "PrimaryImageAttribute"
      description: "Logical name of the primary image attribute"
      iscomputed: false
      isreadonly: false
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version number of Entity Image Configuration."
      iscomputed: false
      isreadonly: true
# This entity has no lookup properties
# This entity has no single-valued navigation properties
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: entityimageconfig_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_entityimageconfig
  - name: entityimageconfig_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_entityimageconfig
  - name: entityimageconfig_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_entityimageconfig
  - name: entityimageconfig_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_entityimageconfig
  - name: entityimageconfig_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_entityimageconfig
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the entityimageconfig entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the entityimageconfig entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_ImageConfiguration
    description: ""
# This entity has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex