### YamlMime:OData
uid: Microsoft.Dynamics.CRM.environmentvariabledefinition
name: "environmentvariabledefinition"
type: entitytype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement environmentvariabledefinition EntityType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: c642b9a6-f695-461c-aff0-c6325430cfb8
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the environmentvariabledefinition entitytype."
description: "Contains information about the settable variable: its type, default value, and etc."
header:
  entity_set_path: "[organization URI]/api/data/v9.0/environmentvariabledefinitions"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: Environment Variable Definition
  primary_key: environmentvariabledefinitionid
  primary_name_attribute: schemaname
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: defaultvalue
      type: Edm.String
      display_name: "Default Value"
      description: "Default variable value to be used if no associated EnvironmentVariableValue entities exist."
      iscomputed: false
      isreadonly: false
    - name: description
      type: Edm.String
      display_name: "Description"
      description: "Description of the variable definition."
      iscomputed: false
      isreadonly: false
    - name: displayname
      type: Edm.String
      display_name: "Display Name"
      description: "Display Name of the variable definition."
      iscomputed: false
      isreadonly: false
    - name: environmentvariabledefinitionid
      type: Edm.Guid
      display_name: "Environment Variable Definition"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: environmentvariabledefinitionidunique
      type: Edm.Guid
      display_name: ""
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: hint
      type: Edm.String
      display_name: "Hint"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: introducedversion
      type: Edm.String
      display_name: "Introduced Version"
      description: "Version in which the form is introduced."
      iscomputed: false
      isreadonly: false
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Customizable"
      description: "Tells whether the component can be customized."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: isrequired
      type: Edm.Boolean
      display_name: "Is Required"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Yes"
        - value: 0
          label: "No"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: schemaname
      type: Edm.String
      display_name: "Schema Name"
      description: "Unique entity name."
      iscomputed: false
      isreadonly: false
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the Environment Variable Definition"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Active"
        - value: 1
          label: "Inactive"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the Environment Variable Definition"
      iscomputed: false
      isreadonly: false
      options:
        - value: 1
          label: "Active"
        - value: 2
          label: "Inactive"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: type
      type: Edm.Int32
      display_name: "Type"
      description: "Environment variable value type."
      iscomputed: false
      isreadonly: false
      options:
        - value: 100000000
          label: "String"
        - value: 100000001
          label: "Number"
        - value: 100000002
          label: "Boolean"
        - value: 100000003
          label: "JSON"
        - value: 100000004
          label: "Connection reference"
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: valueschema
      type: Edm.String
      display_name: "Value Schema"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_environmentvariabledefinition_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_environmentvariabledefinition_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_environmentvariabledefinition_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_environmentvariabledefinition_modifiedonbehalfby
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_environmentvariabledefinition
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_environmentvariabledefinition
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_environmentvariabledefinition
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_environmentvariabledefinition
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: environmentvariabledefinition_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_environmentvariabledefinition
  - name: environmentvariabledefinition_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_environmentvariabledefinition
  - name: environmentvariabledefinition_DuplicateBaseRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: baserecordid_environmentvariabledefinition
  - name: environmentvariabledefinition_DuplicateMatchingRecord
    type: Microsoft.Dynamics.CRM.duplicaterecord
    partner: duplicaterecordid_environmentvariabledefinition
  - name: environmentvariabledefinition_environmentvariablevalue
    type: Microsoft.Dynamics.CRM.environmentvariablevalue
    partner: EnvironmentVariableDefinitionId
  - name: environmentvariabledefinition_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_environmentvariabledefinition
  - name: environmentvariabledefinition_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_environmentvariabledefinition
  - name: environmentvariabledefinition_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_environmentvariabledefinition
  - name: environmentvariabledefinition_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_environmentvariabledefinition
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the environmentvariabledefinition entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
solutions:
  description: "The following solutions include the environmentvariabledefinition entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.EnvironmentVariables
    description: ""
# This entity has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex