### YamlMime:OData
uid: Microsoft.Dynamics.CRM.msdyn_aiconfiguration
name: "msdyn_aiconfiguration"
type: entitytype
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement msdyn_aiconfiguration EntityType Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 5687aab5-3741-4b1b-b216-5c6b4239fe25
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the msdyn_aiconfiguration entitytype."
# This entity doesn't have a description
header:
  entity_set_path: "[organization URI]/api/data/v9.0/msdyn_aiconfigurations"
  base_type: Microsoft.Dynamics.CRM.crmbaseentity
  display_name: AI Configuration
  primary_key: msdyn_aiconfigurationid
  primary_name_attribute: msdyn_name
  operations_supported:
  - POST
  - GET
  - PATCH
  - DELETE
namespace: Microsoft.Dynamics.CRM
properties:
  description: "Properties represent fields of data stored in the entity.Some properties are read-only."
  property_items:
    - name: componentstate
      type: Edm.Int32
      display_name: "Component State"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
      options:
        - value: 0
          label: "Published"
        - value: 1
          label: "Unpublished"
        - value: 2
          label: "Deleted"
        - value: 3
          label: "Deleted Unpublished"
    - name: createdon
      type: Edm.DateTimeOffset
      display_name: "Created On"
      description: "Date and time when the record was created."
      iscomputed: false
      isreadonly: true
    - name: importsequencenumber
      type: Edm.Int32
      display_name: "Import Sequence Number"
      description: "Sequence number of the import that created this record."
      iscomputed: false
      isreadonly: false
    - name: introducedversion
      type: Edm.String
      display_name: "Introduced Version"
      description: "Version in which the form is introduced."
      iscomputed: false
      isreadonly: false
    - name: iscustomizable
      type: Microsoft.Dynamics.CRM.BooleanManagedProperty
      display_name: "Customizable"
      description: "Tells whether the component can be customized."
      iscomputed: false
      isreadonly: false
    - name: ismanaged
      type: Edm.Boolean
      display_name: "Is Managed"
      description: "Indicates whether the solution component is part of a managed solution."
      iscomputed: false
      isreadonly: true
      options:
        - value: 1
          label: "Managed"
        - value: 0
          label: "Unmanaged"
    - name: modifiedon
      type: Edm.DateTimeOffset
      display_name: "Modified On"
      description: "Date and time when the record was modified."
      iscomputed: false
      isreadonly: true
    - name: msdyn_aiconfigurationid
      type: Edm.Guid
      display_name: "AIConfiguration"
      description: "Unique identifier for entity instances"
      iscomputed: false
      isreadonly: false
    - name: msdyn_aiconfigurationidunique
      type: Edm.Guid
      display_name: ""
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: msdyn_customconfiguration
      type: Edm.String
      display_name: "CustomConfiguration"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_databinding
      type: Edm.String
      display_name: "DataBinding"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_lasterrors
      type: Edm.String
      display_name: "LastErrors"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_lasttrainorrundate
      type: Edm.DateTimeOffset
      display_name: "LastTrainOrRunDate"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_majoriterationnumber
      type: Edm.Int32
      display_name: "MajorIterationNumber"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_minoriterationnumber
      type: Edm.Int32
      display_name: "MinorIterationNumber"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_modeldata
      type: Edm.String
      display_name: "ModelData"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_modelglobalexplainability
      type: Edm.String
      display_name: "ModelGlobalExplainability"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_modelperformance
      type: Edm.String
      display_name: "ModelPerformance"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_modelprovisioningmetadata
      type: Edm.String
      display_name: "ModelProvisioningMetadata"
      description: "Model Provisioning Metadata"
      iscomputed: false
      isreadonly: false
    - name: msdyn_modelprovisioningstatus
      type: Edm.String
      display_name: "ModelProvisioningStatus"
      description: "Model Provisioning Status"
      iscomputed: false
      isreadonly: false
    - name: msdyn_modelrundataspecification
      type: Edm.String
      display_name: "ModelRunDataSpecification"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_name
      type: Edm.String
      display_name: "Name"
      description: "The name of the custom entity."
      iscomputed: false
      isreadonly: false
    - name: msdyn_resourceinfo
      type: Edm.String
      display_name: "ResourceInfo"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_runconfiguration
      type: Edm.String
      display_name: "RunConfiguration"
      description: "Run Configuration"
      iscomputed: false
      isreadonly: false
    - name: msdyn_schedulingoptions
      type: Edm.String
      display_name: "SchedulingOptions"
      description: ""
      iscomputed: false
      isreadonly: false
    - name: msdyn_templateversion
      type: Edm.Int32
      display_name: "TemplateVersion"
      description: "Template Version"
      iscomputed: false
      isreadonly: false
    - name: msdyn_type
      type: Edm.Int32
      display_name: "Type"
      description: ""
      iscomputed: false
      isreadonly: false
      options:
        - value: 190690000
          label: "TrainingConfiguration"
        - value: 190690001
          label: "RunConfiguration"
    - name: overriddencreatedon
      type: Edm.DateTimeOffset
      display_name: "Record Created On"
      description: "Date and time that the record was migrated."
      iscomputed: false
      isreadonly: false
    - name: overwritetime
      type: Edm.DateTimeOffset
      display_name: "Record Overwrite Time"
      description: "For internal use only."
      iscomputed: false
      isreadonly: true
    - name: solutionid
      type: Edm.Guid
      display_name: "Solution"
      description: "Unique identifier of the associated solution."
      iscomputed: false
      isreadonly: true
    - name: statecode
      type: Edm.Int32
      display_name: "Status"
      description: "Status of the AIConfiguration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Draft"
        - value: 1
          label: "InProgress"
        - value: 2
          label: "Done"
        - value: 3
          label: "Failed"
    - name: statuscode
      type: Edm.Int32
      display_name: "Status Reason"
      description: "Reason for the status of the AIConfiguration"
      iscomputed: false
      isreadonly: false
      options:
        - value: 0
          label: "Draft"
        - value: 1
          label: "Training"
        - value: 2
          label: "Cancelling"
        - value: 3
          label: "Publishing"
        - value: 4
          label: "Unpublishing"
        - value: 5
          label: "Deleting"
        - value: 6
          label: "Trained"
        - value: 7
          label: "Published"
        - value: 8
          label: "Scheduled"
        - value: 9
          label: "TrainFailed"
        - value: 10
          label: "PublishFailed"
        - value: 11
          label: "UnpublishFailed"
        - value: 12
          label: "CancelFailed"
        - value: 13
          label: "DeleteFailed"
        - value: 14
          label: "UnsuccessfulTraining"
    - name: timezoneruleversionnumber
      type: Edm.Int32
      display_name: "Time Zone Rule Version Number"
      description: "For internal use only."
      iscomputed: false
      isreadonly: false
    - name: utcconversiontimezonecode
      type: Edm.Int32
      display_name: "UTC Conversion Time Zone Code"
      description: "Time zone code that was in use when the record was created."
      iscomputed: false
      isreadonly: false
    - name: versionnumber
      type: Edm.Int64
      display_name: "Version Number"
      description: "Version Number"
      iscomputed: false
      isreadonly: true
lookup_properties:
  description: "Lookup properties are read-only, computed properties which contain entity primary key Edm.Guid data for one or more corresponding single-valued navigation properties. More information: [Lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/web-api-types-operations#lookup-properties) and [Retrieve data about lookup properties](https://docs.microsoft.com/dynamics365/customer-engagement/developer/webapi/query-data-web-api#retrieve-data-about-lookup-properties)."
  property_items:
  - name: _createdby_value
    single_valued_navigation_property:
    - createdby
    description: "Unique identifier of the user who created the record."
  - name: _createdonbehalfby_value
    single_valued_navigation_property:
    - createdonbehalfby
    description: "Unique identifier of the delegate user who created the record."
  - name: _modifiedby_value
    single_valued_navigation_property:
    - modifiedby
    description: "Unique identifier of the user who modified the record."
  - name: _modifiedonbehalfby_value
    single_valued_navigation_property:
    - modifiedonbehalfby
    description: "Unique identifier of the delegate user who modified the record."
  - name: _msdyn_aimodelid_value
    single_valued_navigation_property:
    - msdyn_AIModelId
    description: "Unique identifier for AIModel associated with AIConfiguration."
  - name: _msdyn_createdfromconfigurationid_value
    single_valued_navigation_property:
    - msdyn_CreatedFromConfigurationId
    description: ""
  - name: _msdyn_trainedmodelaiconfigurationpareid_value
    single_valued_navigation_property:
    - msdyn_TrainedModelAIConfigurationPareId
    description: "Unique identifier for AIConfiguration associated with AIConfiguration."
  - name: _ownerid_value
    single_valued_navigation_property:
    - ownerid
    description: "Owner Id"
  - name: _owningbusinessunit_value
    single_valued_navigation_property:
    - owningbusinessunit
    description: "Unique identifier for the business unit that owns the record"
  - name: _owningteam_value
    single_valued_navigation_property:
    - owningteam
    description: "Unique identifier for the team that owns the record."
  - name: _owninguser_value
    single_valued_navigation_property:
    - owninguser
    description: "Unique identifier for the user that owns the record."
single_valued_navigation_properties:
  description: "Single-valued navigation properties represent lookup fields where a single entity can be referenced. Each single-valued navigation property has a corresponding partner collection-valued navigation property on the related entity."
  property_items:
  - name: createdby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_aiconfiguration_createdby
  - name: createdonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_aiconfiguration_createdonbehalfby
  - name: modifiedby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_aiconfiguration_modifiedby
  - name: modifiedonbehalfby
    type: Microsoft.Dynamics.CRM.systemuser
    partner: lk_msdyn_aiconfiguration_modifiedonbehalfby
  - name: msdyn_AIModelId
    type: Microsoft.Dynamics.CRM.msdyn_aimodel
    partner: msdyn_aimodel_msdyn_aiconfiguration
  - name: msdyn_CreatedFromConfigurationId
    type: Microsoft.Dynamics.CRM.msdyn_aiconfiguration
    partner: msdyn_createdfromconfiguration_msdyn_toconfiguration
  - name: msdyn_TrainedModelAIConfigurationPareId
    type: Microsoft.Dynamics.CRM.msdyn_aiconfiguration
    partner: msdyn_aiconfiguration_msdyn_aiconfiguration
  - name: ownerid
    type: Microsoft.Dynamics.CRM.principal
    partner: owner_msdyn_aiconfiguration
  - name: owningbusinessunit
    type: Microsoft.Dynamics.CRM.businessunit
    partner: business_unit_msdyn_aiconfiguration
  - name: owningteam
    type: Microsoft.Dynamics.CRM.team
    partner: team_msdyn_aiconfiguration
  - name: owninguser
    type: Microsoft.Dynamics.CRM.systemuser
    partner: user_msdyn_aiconfiguration
collection_valued_navigation_properties:
  description: "Collection-valued navigation properties represent collections of entities which may represent either a one-to-many (1:N) or many-to-many (N:N) relationship between the entities."
  property_items:
  - name: msdyn_aiconfiguration_AsyncOperations
    type: Microsoft.Dynamics.CRM.asyncoperation
    partner: regardingobjectid_msdyn_aiconfiguration
  - name: msdyn_aiconfiguration_BulkDeleteFailures
    type: Microsoft.Dynamics.CRM.bulkdeletefailure
    partner: regardingobjectid_msdyn_aiconfiguration
  - name: msdyn_aiconfiguration_MailboxTrackingFolders
    type: Microsoft.Dynamics.CRM.mailboxtrackingfolder
    partner: regardingobjectid_msdyn_aiconfiguration
  - name: msdyn_aiconfiguration_msdyn_aiconfiguration
    type: Microsoft.Dynamics.CRM.msdyn_aiconfiguration
    partner: msdyn_TrainedModelAIConfigurationPareId
  - name: msdyn_aiconfiguration_msdyn_aiodtrainingimage
    type: Microsoft.Dynamics.CRM.msdyn_aiodtrainingimage
    partner: msdyn_AIConfigurationId
  - name: msdyn_aiconfiguration_PrincipalObjectAttributeAccesses
    type: Microsoft.Dynamics.CRM.principalobjectattributeaccess
    partner: objectid_msdyn_aiconfiguration
  - name: msdyn_aiconfiguration_ProcessSession
    type: Microsoft.Dynamics.CRM.processsession
    partner: regardingobjectid_msdyn_aiconfiguration
  - name: msdyn_aiconfiguration_SyncErrors
    type: Microsoft.Dynamics.CRM.syncerror
    partner: regardingobjectid_msdyn_aiconfiguration
  - name: msdyn_aiodlabel_msdyn_aiconfiguration
    type: Microsoft.Dynamics.CRM.msdyn_aiodlabel
    partner: msdyn_aiodlabel_msdyn_aiconfiguration
  - name: msdyn_createdfromconfiguration_msdyn_toconfiguration
    type: Microsoft.Dynamics.CRM.msdyn_aiconfiguration
    partner: msdyn_CreatedFromConfigurationId
  - name: msdyn_msdyn_aiconfiguration_msdyn_aifptrainingdocument_AIConfigurationId
    type: Microsoft.Dynamics.CRM.msdyn_aifptrainingdocument
    partner: msdyn_AIConfigurationId
# This entity has no derived entities.
operations:
  description: "The following operations can be used with the msdyn_aiconfiguration entity type."
  operation_items:
  - name: Microsoft.Dynamics.CRM.CancelTraining
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.GrantAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.IsValidStateTransition
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ModifyAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.PublishAIConfiguration
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.QuickTest
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.RetrievePrincipalAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RetrieveSharedPrincipalsAndAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.RevokeAccess
    binding_type: "Not Bound"
  - name: Microsoft.Dynamics.CRM.ScheduleTraining
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.Train
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.UnpublishAIConfiguration
    binding_type: "Entity"
  - name: Microsoft.Dynamics.CRM.UnscheduleTraining
    binding_type: "Entity"
solutions:
  description: "The following solutions include the msdyn_aiconfiguration entity type."
  solution_items:
  - type: Microsoft.Dynamics.CRM.msdyn_AISolution
    description: ""
# This entity has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex