### YamlMime:OData
uid: Microsoft.Dynamics.CRM.PublishAIConfiguration
name: "PublishAIConfiguration"
type: action
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement PublishAIConfiguration Action Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 819f663b-5109-44a3-9620-de310c1936d8
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the PublishAIConfiguration Action."
namespace: Microsoft.Dynamics.CRM
# This Action has no description.
owningsolution: Microsoft.Dynamics.CRM.System
bound_entities:
  description: "Bound actions are invoked by appending the action name to the URI representing an entity or collection."
  bound_entity_items:
  - entity_type: Microsoft.Dynamics.CRM.msdyn_aiconfiguration
    binding_type: entity
parameters:
  description: "Parameters allow for data to be passed to the action."
  parameter_items:
  - name: version
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
return_type:
  description: "The PublishAIConfiguration action returns the following value."
  iscollection: false
  nullable: false
  type: Microsoft.Dynamics.CRM.PublishAIConfigurationResponse
# This action has no identified unbound entities.
# This action has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex