### YamlMime:OData
uid: Microsoft.Dynamics.CRM.ContainValues
name: "ContainValues"
type: queryfunction
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement ContainValues Query Function Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 9faa92c0-5ca5-41bf-8976-f4a3842b2087
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the ContainValues Query Function."
namespace: Microsoft.Dynamics.CRM
description: ""
parameters:
  description: "Parameters allow for data to be passed to the query function."
  parameter_items:
  - name: "PropertyName"
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
  - name: "PropertyValues"
    type: Edm.String
    nullable: false
    unicode: false
    description: ""
syntax_example: "?$filter=Microsoft.Dynamics.CRM.ContainValues(PropertyName=@p1,PropertyValues=@p2)&@p1='name'&@p2=['value','value']"
# This query function has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex