### YamlMime:OData
uid: Microsoft.Dynamics.CRM.RetrieveDeploymentLicenseType
name: "RetrieveDeploymentLicenseType"
type: function
metadata: 
  title: "Common Data Service and Dynamics 365 Customer Engagement RetrieveDeploymentLicenseType Function Reference | MicrosoftDocs"
  ms.date: "05/03/2020"
  ms.service: "crm-online"
  ms.topic: "reference"
  ms.assetid: 1944adce-7d01-4a6c-bc44-1d0613310af6
  author: "KumarVivek"
  ms.author: "kvivek"
  manager: "Annbe"
  meta-description: "Reference information about the RetrieveDeploymentLicenseType Function."
namespace: Microsoft.Dynamics.CRM
description: "Retrieves the type of license for a deployment of Microsoft Dynamics 365.  "
iscomposable: false
# This function is not bound to any entities.
isbound: false
# This function has no parameters.
hasparameters: false
return_type:
  description: "The RetrieveDeploymentLicenseType function returns the following value."
  type: Microsoft.Dynamics.CRM.RetrieveDeploymentLicenseTypeResponse
  iscollection: false
  nullable: false
# This function no specific entities for this function identified.
# This function has no remarks.
href_see_also:
- text: "Use the Common Data Service Web API"
  href: "https://docs.microsoft.com/powerapps/developer/common-data-service/webapi/overview"
xref_see_also:
- Microsoft.Dynamics.CRM.EntityTypeIndex
- Microsoft.Dynamics.CRM.ActionIndex
- Microsoft.Dynamics.CRM.FunctionIndex
- Microsoft.Dynamics.CRM.QueryFunctionIndex
- Microsoft.Dynamics.CRM.ComplexTypeIndex
- Microsoft.Dynamics.CRM.EnumTypeIndex
- Microsoft.Dynamics.CRM.MetadataEntityTypeIndex
- Microsoft.Dynamics.CRM.SolutionIndex